jobs:
  pr:
    if: github.repository_owner == 'jenkins-x'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: build-make-test
      uses: docker://golang:1.17.9
      with:
        args: -c "make test linux"
        entrypoint: /bin/sh
"on":
  push:
    branches-ignore:
    - main
    - master
